describe('Teste de API da requisição PATCH https://api.restful-api.dev/objects/id', () => {
    before(() => {
        Cypress.config('baseUrl', 'https://api.restful-api.dev')
      })

    it('Deve atualizar um campo específico de um objeto', () => {
        cy.makeRequest('PATCH', '/objects/ff808181932badb601959ffd5bc85e43', {"name": "Notebook da maria"}).then((response) => {
            cy.log(JSON.stringify(response.body))
            expect(response.status).to.eq(200)
            expect(response.body).to.haveOwnProperty('id')
            expect(response.body).to.haveOwnProperty('name')
            expect(response.body).to.haveOwnProperty('data')
            expect(response.body.name).to.be.equal('Notebook da maria')
            expect(response.body).to.haveOwnProperty('updatedAt')
        })
    })

    it('Deve tentar atualizar um objeto que possui ID reservada', () => {
        cy.makeRequest('PATCH', '/objects/7', {"name": "Notebook da maria"}).then((response) => {
            cy.log(JSON.stringify(response.body))
            expect(response.status).to.eq(405)
            expect(response.body).to.be.an('Object')
            expect(response.body).to.haveOwnProperty('error')
            expect(response.body.error).to.be.equal('7 is a reserved id and the data object of it cannot be overridden. You can create a new object via POST request and use new generated by id from it to send a PATCH request.')
        })
    })

    it('Deve tentar atualizar um objeto sem enviar campos necessários', () => {
        cy.makeRequest('PATCH', '/objects/ff808181932badb601959ffd5bc85e43').then((response) => {
            cy.log(JSON.stringify(response.body))
            expect(response.status).to.eq(400)
            expect(response.body).to.be.an('Object')
            expect(response.body).to.haveOwnProperty('error')
            expect(response.body.error).to.be.equal('400 Bad Request. If you are trying to create or update the data, potential issue is that you are sending incorrect body json or it is missing at all.')
        })
    })
})